image: microsoft/dotnet:latest

stages:
  - build
  - test

before_script:
  - "dotnet restore src"
  - "dotnet restore tests"

project-debug:
  stage: build
  script:
    - "cd src"
    - "dotnet publish"
project-debug:
  stage: test
  script:
    - "cd tests"
    - "dotnet test /p:CollectCoverage=true"
